### ISSUE TITLE
twitter.comからx.comにリダイレクトされるようになったので、動作しなくなった

### ISSUE THREAD

**Issue by AzukiShiratama** [bootjp/disable_twitter_shortcut#5]
数日前にx.comにリダイレクトされる仕様が導入されたようなので、こちらの拡張機能が動作しなくなりました。
対応URLにx.comの追加をお願いいたします。

**Comment by bootjp** [comment]
ご報告ありがとうございます。

本日配信された version 0.0.5にて修正しております。
<img width="408" alt="image" src="https://github.com/bootjp/disable_twitter_shortcut/assets/1306365/8553f802-6c77-4594-ae17-725face1a7b1">
